// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALmZ10Oh7B-8W8Qf8QEXQtc4lDC8NlLjc',
    appId: '1:361780455797:web:af4837d64059aaf5358b3c',
    messagingSenderId: '361780455797',
    projectId: 'neonmatch-8b6d1',
    authDomain: 'neonmatch-8b6d1.firebaseapp.com',
    storageBucket: 'neonmatch-8b6d1.firebasestorage.app',
    measurementId: 'G-VFPWSRM1N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_21nwhPiHfmZtTr_eeHc_WyHgQzq8fI4',
    appId: '1:361780455797:android:5c1ac3c32eaa8afd358b3c',
    messagingSenderId: '361780455797',
    projectId: 'neonmatch-8b6d1',
    storageBucket: 'neonmatch-8b6d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBByDEpNY1l8RpTeEqFa0wtlkgfvn2R3Ns',
    appId: '1:361780455797:ios:4d42841730084e2b358b3c',
    messagingSenderId: '361780455797',
    projectId: 'neonmatch-8b6d1',
    storageBucket: 'neonmatch-8b6d1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBByDEpNY1l8RpTeEqFa0wtlkgfvn2R3Ns',
    appId: '1:361780455797:ios:4d42841730084e2b358b3c',
    messagingSenderId: '361780455797',
    projectId: 'neonmatch-8b6d1',
    storageBucket: 'neonmatch-8b6d1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALmZ10Oh7B-8W8Qf8QEXQtc4lDC8NlLjc',
    appId: '1:361780455797:web:7c3d5923ac392321358b3c',
    messagingSenderId: '361780455797',
    projectId: 'neonmatch-8b6d1',
    authDomain: 'neonmatch-8b6d1.firebaseapp.com',
    storageBucket: 'neonmatch-8b6d1.firebasestorage.app',
    measurementId: 'G-GL8G0TJWXX',
  );

}